### ISSUE TITLE
Getting 404 for <domain>/svg/ when using behind reverse proxy (Nginx)

### ISSUE THREAD

**Issue by dudutwizer** [linuxserver/docker-nextcloud#229]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Topology: 
Reverse proxy (Nginx) with SSL termination -> Next cloud docker

The app is working but slow I noticed that I'm getting 404 just for the `SVG` path. 

------------------------------

## Expected Behavior
No 404

## Current Behavior
Getting 404 for the /SVG/ 

## Environment
**OS:** Ubuntu
**CPU architecture:** x86_64/arm32/arm64: x86_64

**How docker service was installed:**
 Official docker repo

## Docker logs

# Nextcloud Instance:
next cloud docker

```
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 40-config: executing...
[cont-init.d] 40-config: exited 0.
[cont-init.d] 50-install: executing...
[cont-init.d] 50-install: exited 0.
[cont-init.d] 60-memcache: executing...
[cont-init.d] 60-memcache: exited 0.
[cont-init.d] 70-aliases: executing...
[cont-init.d] 70-aliases: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```
```
 tail ./log/php/error.log
[24-Jan-2022 10:40:52] NOTICE: Terminating ...
[24-Jan-2022 10:40:52] NOTICE: exiting, bye-bye!
[24-Jan-2022 10:41:01] NOTICE: fpm is running, pid 392
[24-Jan-2022 10:41:01] NOTICE: ready to handle connections
[24-Jan-2022 10:41:07] WARNING: [pool www] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), spawning 8 children, there are 0 idle, and 5 total children
[24-Jan-2022 10:41:08] WARNING: [pool www] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), spawning 16 children, there are 0 idle, and 6 total children
[24-Jan-2022 10:41:09] WARNING: [pool www] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), spawning 32 children, there are 0 idle, and 7 total children
[24-Jan-2022 10:41:10] WARNING: [pool www] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), spawning 32 children, there are 0 idle, and 8 total children
[24-Jan-2022 10:41:11] WARNING: [pool www] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), spawning 32 children, there are 0 idle, and 9 total children
[24-Jan-2022 10:41:21] WARNING: [pool www] server reached pm.max_children setting (10), consider raising it
```

```
 tail ./log/nginx/error.log
2022/01/24 10:43:21 [error] 404#404: *393 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] timeout expired in /config/www/nextcloud/lib/private/DB/Connection.php:87
Stack trace:
#0 /config/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1486): OC\DB\Connection->connect()
#1 /config/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1014): Doctrine\DBAL\Connection->getWrappedConnection()
#2 /config/www/nextcloud/lib/private/DB/Connection.php(231): Doctrine\DBAL\Connection->executeQuery()
#3 /config/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php(210): OC\DB\Connection->executeQuery()
#4 /config/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(287): Doctrine\DBAL\Query\QueryBuilder->execute()
#5 /config/www/nextcloud/lib/private/AppConfig.php(344): OC\DB\QueryBuilder\QueryBuilder->execute()
#6 /config/www/nextcloud/lib/private/AppConfig.php(109): OC\AppConfig->loadConfigValues()
#7 /config/www/ne" while reading response header from upstream, client: 10.0.2.1, server: <domain>, request: "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "<domain>"
```

# Here is the issue
```
tail ./log/nginx/access.log
10.0.2.1 - - [24/Jan/2022:10:51:31 +0000] "GET /svg/contacts/eye?color=f2f2f2&v=1 HTTP/1.1" 404 4620 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15"
10.0.2.1 - - [24/Jan/2022:10:51:31 +0000] "GET /svg/contacts/up?color=f2f2f2&v=1 HTTP/1.1" 404 4619 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15"
10.0.2.1 - - [24/Jan/2022:10:51:31 +0000] "GET /svg/forms/answer-long?color=f2f2f2&v=1 HTTP/1.1" 404 4618 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15"
10.0.2.1 - - [24/Jan/2022:10:51:31 +0000] "GET /svg/deck/archive?color=f2f2f2&v=1 HTTP/1.1" 404 4614 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15"
10.0.2.1 - - [24/Jan/2022:10:51:31 +0000] "GET /svg/deck/toggle-view-collapse?color=f2f2f2&v=1 HTTP/1.1" 404 4621 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15"
10.0.2.1 - - [24/Jan/2022:10:51:31 +0000] "GET /svg/deck/clone?color=f2f2f2&v=1 HTTP/1.1" 404 4622 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15"
10.0.2.1 - - [24/Jan/2022:10:51:31 +0000] "GET /svg/deck/toggle-view-expand?color=f2f2f2&v=1 HTTP/1.1" 404 4617 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15"
10.0.2.1 - - [24/Jan/2022:10:51:32 +0000] "GET /svg/deck/filter?color=f2f2f2&v=1 HTTP/1.1" 404 4619 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15"
10.0.2.1 - - [24/Jan/2022:10:51:32 +0000] "GET /svg/forms/answer-dropdown?color=f2f2f2&v=1 HTTP/1.1" 404 4619 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15"
10.0.2.1 - - [24/Jan/2022:10:51:32 +0000] "GET /svg/collectives/sort-by-alpha?color=f2f2f2&v=1 HTTP/1.1" 404 4616 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15"
```

# NextCloud Nginx default 
```
server {
    listen 80;
    listen [::]:80;
    #server_name _;
    server_name <domain-name>;
    #ssl_certificate /config/keys/cert.crt; (I disabled the SSL because I'm using Nginx reverse proxy)
    #ssl_certificate_key /config/keys/cert.key;
    #include /config/nginx/ssl.conf;
    #if ($lan-ip = yes) { set $allowed_mycountry yes; } #Check for a LAN IP
    #if ($allowed_mycountry = no) { return 404; } #Check the country filter
    # Add headers to serve security related headers
    # Before enabling Strict-Transport-Security headers please read into this
    # topic first.
    add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;" always;
...
all default 
```
```
"./www/nextcloud/config/config.php" 49L, 1294C                                                                                              21,3          All
<?php
$CONFIG = array (
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'datadirectory' => '/data',
  'instanceid' => '<id>',
  'passwordsalt' => '<password>',
  'secret' => '<secret>',
  'trusted_proxies' =>
   array (
           0 => '<reverse proxy address>',
           1 => '<lan CIDR address>',
   ),
    'trusted_domains' =>
  array (
    0 => '<domain>',
  ),
  'dbtype' => 'pgsql',
  'version' => '22.0.0.11',
  'overwrite.cli.url' => 'https://<domain>',
  'overwritehost' => "<domain>",
  'overwriteprotocol' => 'https',
  'dbname' => '<db-name>',
  'dbhost' => '<ip>:<port>',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '<user>',
  'dbpassword' => '<password>',
  'installed' => true,
  'log_rotate_size' => 1024,
  'twofactor_enforced' => 'false',
  'twofactor_enforced_groups' =>
  array (
  ),
  'twofactor_enforced_excluded_groups' =>
  array (
  ),
  'app_install_overwrite' =>
  array (
    0 => 'xray',
    1 => 'limit_login_to_ip',
  ),
  'maintenance' => false,
  'mail_from_address' => 'NextCloud',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_domain' => '<domain>',
  'mail_smtphost' => '<ip>',
  'mail_smtpport' => '2525',
);
~
~
```

# reverse Proxy settings

```
server {
listen 443 ssl http2;
listen [::]:443 ssl http2;

root /config/www;
index index.html index.htm index.php;

server_name <domain>;
include /config/nginx/ssl.conf;
client_max_body_size 0;
underscores_in_headers on;


# display real ip in nginx logs when connected through reverse proxy via docker network
set_real_ip_from <docker-cidr>/16;
real_ip_header X-Forwarded-For;

location / {
    proxy_headers_hash_max_size 512;
    proxy_headers_hash_bucket_size 64;
    proxy_max_temp_file_size 0;
    proxy_pass http://<privateIPAddress>/; #the next cloud instance 
    proxy_read_timeout 3600;
    proxy_http_version 1.1;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
}

location /.well-known/carddav {
    return 301 $scheme://$host/remote.php/dav;
}

location /.well-known/cal
```

**Comment by Watish** [comment]
Maybe you should change config file in /var/www/html/nextcloud/config/config.php before you use nginx proxy
