### ISSUE TITLE
Fresh install and my database is already corrupt?

### ISSUE THREAD

**Issue by Kurasami** [linuxserver/docker-nextcloud#310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Fresh install of this, just made a user and I already got this error:

![image](https://github.com/linuxserver/docker-nextcloud/assets/77334270/62e39656-2b78-494c-9988-ccb6643ff0c9)

### Steps To Reproduce

Just install the docker container

Make a user

Check the logs

### Environment

```markdown
- OS: Unraid
- How docker service was installed: via Unraid

Installed this container via Unraid. Nothing more.
```

### CPU architecture

x86-64

### Docker creation

```bash
N/A
```

### Container logs

```bash
root@Tower:~# docker logs nextcloud
[migrations] started
[migrations] 01-nginx-site-confs-default: executing...
[migrations] 01-nginx-site-confs-default: succeeded
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

Setting resolver to  127.0.0.11
Setting worker_processes to 12
generating self-signed keys in /config/keys, you can replace these with your own keys if required
..+.+...+.........+...+.........+.....+.............+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*........+.........+..+...+.......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*................+..+.+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
..+...............+..+....+.....+......+.........+......+......+...+....+......+...........+.+.........+.....+..........+......+...+..+...+.........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*...+.+........+......+....+...+.........+...+...+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*............+...+.....+.+........+...+.......+......+..+...+....+...............+..+...+.+.....+.+......+.........+...+.....+......+......+.+..+.+.................+.........+.+............+.....+.......+.....+....+.....+.......+..+.+......+...+..+....+.....+.+..................+.....+...+...+.+......+........+..........+..+.......+......+......+......+.....+...+....+..+................+..+......+.......+..+.......+.....+.+.....+..........+..+................+..+...+.+......+........+......+...+......+.......+...+..+.......+...+..+...+...+.......+.....+.........+.+...+....................+....+...+........+.......+..+.+............+..+.......+.....+...+.......+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-----
# do daily/weekly/monthly maintenance
# min   hour    day     month   weekday command
*/15    *       *       *       *       run-parts /etc/periodic/15min
0       *       *       *       *       run-parts /etc/periodic/hourly
0       2       *       *       *       run-parts /etc/periodic/daily
0       3       *       *       6       run-parts /etc/periodic/weekly
0       5       1       *       *       run-parts /etc/periodic/monthly
# nextcloud cron
*/5     *       *       *       *       s6-setuidgid abc php -f /config/www/nextcloud/cron.php
[custom-init] No custom files found, skipping...
[ls.io-init] done.
Exception: Not installed in /config/www/nextcloud/lib/base.php:281
Stack trace:
#0 /config/www/nextcloud/lib/base.php(697): OC::checkInstalled()
#1 /config/www/nextcloud/lib/base.php(1165): OC::init()
#2 /config/www/nextcloud/cron.php(43): require_once('...')
#3 {main}
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

using keys found in /config/keys
[custom-init] No custom files found, skipping...
[ls.io-init] done.
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

using keys found in /config/keys
[custom-init] No custom files found, skipping...
[ls.io-init] done.
root@Tower:~#
```

**Comment by aptalca** [comment]
There is no database until you go through the wizard. You either had existing data from before or you mapped the config folder somewhere with an existing and corrupt db.
