### ISSUE TITLE
[BUG] OCC app:update --all and updater.phar failing

### ISSUE THREAD

**Issue by bsasealteam6** [linuxserver/docker-nextcloud#312]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When I try to connect to my nextcloud, I get this error

```
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.
```

Also, if I try to run updater.phar, I get this error:
```
docker exec -it nextcloud updater.phar
Nextcloud Updater - version: v26.0.0beta2-9-g64e2e4c dirty

The posix extensions are required - see http://php.net/manual/en/book.posix.php
```

And if I run `occ apt:update --all` I get this error:
```
occ app:update --all
An unhandled exception has been thrown:
Error: Class "PDO" not found in /config/www/nextcloud/lib/private/DB/Connection.php:156
Stack trace:
#0 /config/www/nextcloud/lib/private/AppConfig.php(415): OC\DB\Connection->getQueryBuilder()
#1 /config/www/nextcloud/lib/private/AppConfig.php(184): OC\AppConfig->loadConfigValues()
#2 /config/www/nextcloud/lib/private/AppConfig.php(374): OC\AppConfig->getApps()
#3 /config/www/nextcloud/lib/private/legacy/OC_App.php(976): OC\AppConfig->getValues()
#4 /config/www/nextcloud/lib/private/Server.php(729): OC_App::getAppVersions()
#5 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\Server->OC\{closure}()
#6 /config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#7 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet()
#8 /config/www/nextcloud/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query()
#9 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query()
#10 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(193): OC\AppFramework\Utility\SimpleContainer->get()
#11 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#12 /config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#13 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet()
#14 /config/www/nextcloud/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query()
#15 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query()
#16 /config/www/nextcloud/lib/private/Server.php(1110): OC\AppFramework\Utility\SimpleContainer->get()
#17 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\Server->OC\{closure}()
#18 /config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#19 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet()
#20 /config/www/nextcloud/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query()
#21 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query()
#22 /config/www/nextcloud/lib/private/Server.php(2065): OC\AppFramework\Utility\SimpleContainer->get()
#23 /config/www/nextcloud/lib/private/Files/View.php(119): OC\Server->getLockingProvider()
#24 /config/www/nextcloud/lib/private/Server.php(464): OC\Files\View->__construct()
#25 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\Server->OC\{closure}()
#26 /config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#27 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet()
#28 /config/www/nextcloud/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query()
#29 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query()
#30 /config/www/nextcloud/lib/private/Server.php(1467): OC\AppFramework\Utility\SimpleContainer->get()
#31 /config/www/nextcloud/lib/base.php(625): OC\Server->boot()
#32 /config/www/nextcloud/lib/base.php(1167): OC::init()
#33 /config/www/nextcloud/console.php(48): require_once('...')
#34 /config/www/nextcloud/occ(11): require_once('...')
#35 {main}% 
```

### Expected Behavior

For navigating to web page: see nextcloud dashboard
For updater.phar: Updates server

### Steps To Reproduce

All I did was upgrade from your last docker container to this one:
```zsh
docker-compose pull && docker-compose up -d
```

### Environment

```markdown
- OS: Debian 11
- How docker service was installed:
Apt using Docker's Apt repo.  Docker version 24.0.2, build cb74dfc 
docker-compose version 1.29.2, build unknown installed through pipx
```

### CPU architecture

x86-64

### Docker creation

```bash
nextcloud:
    image: lscr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
      - DOCKER_MODS=linuxserver/mods:nextcloud-mediadc|linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=clamav|ffmpeg|npm|nodejs|make|git|composer
    volumes:
      - /data/nextcloud/config:/config
      - /data/nextcloud/data:/data
    # ports:
    #   - 3565:443
    restart: unless-stopped
    networks:
      - nextcloud
      - proxy
```

### Container logs

```bash
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Adding linuxserver/mods:nextcloud-mediadc to container
[mod-init] Downloading linuxserver/mods:nextcloud-mediadc from lscr.io
[mod-init] Installing linuxserver/mods:nextcloud-mediadc
[mod-init] linuxserver/mods:nextcloud-mediadc applied to container
[mod-init] Adding linuxserver/mods:universal-package-install to container
[mod-init] Downloading linuxserver/mods:universal-package-install from lscr.io
[mod-init] Installing linuxserver/mods:universal-package-install
[mod-init] linuxserver/mods:universal-package-install applied to container
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

using keys found in /config/keys
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│            │ 2023-04-13 │ /config/nginx/site-confs/default.conf                                  │
│ 2021-10-24 │ 2023-04-13 │ /config/nginx/nginx.conf                                               │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
**** The following site-confs have extensions other than .conf ****
**** This may be due to user customization. ****
**** You should review the files and rename them to use the .conf extension or remove them. ****
**** nginx.conf will only include site-confs with the .conf extension. ****
/config/nginx/site-confs/default
**** Adding clamav to OS package install list ****
**** Adding ffmpeg to OS package install list ****
**** Adding npm to OS package install list ****
**** Adding nodejs to OS package install list ****
**** Adding make to OS package install list ****
**** Adding git to OS package install list ****
**** Adding composer to OS package install list ****
**** Adding pillow-heif, hexhamming, pywavelets and their deps to package install lists ****
[mod-init] **** Installing all mod packages ****
fetch http://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
(1/74) Installing json-c (0.16-r3)
(2/74) Installing libmspack (0.11_alpha-r0)
(3/74) Installing clamav-libs (1.1.0-r0)
(4/74) Installing freshclam (1.1.0-r0)
Executing freshclam-1.1.0-r0.pre-install
(5/74) Installing clamav-scanner (1.1.0-r0)
(6/74) Installing clamav-clamdscan (1.1.0-r0)
(7/74) Installing clamav-daemon (1.1.0-r0)
Executing clamav-daemon-1.1.0-r0.pre-install
(8/74) Installing musl-fts (1.2.7-r5)
(9/74) Installing clamav (1.1.0-r0)
(10/74) Installing php81-common (8.1.19-r2)
(11/74) Installing php81 (8.1.19-r2)
(12/74) Installing php81-phar (8.1.19-r2)
(13/74) Installing php81-curl (8.1.19-r2)
(14/74) Installing php81-iconv (8.1.19-r2)
(15/74) Installing php81-mbstring (8.1.19-r2)
(16/74) Installing php81-openssl (8.1.19-r2)
(17/74) Installing php81-zip (8.1.19-r2)
(18/74) Installing composer (2.5.5-r0)
(19/74) Installing make (4.4.1-r1)
(20/74) Installing c-ares (1.19.1-r0)
(21/74) Installing nodejs (18.16.0-r1)
(22/74) Installing npm (9.6.6-r0)
(23/74) Installing mpdecimal (2.5.1-r2)
(24/74) Installing python3 (3.11.3-r11)
(25/74) Installing python3-pycache-pyc0 (3.11.3-r11)
(26/74) Installing pyc (0.1-r0)
(27/74) Installing py3-asn1crypto-pyc (1.5.1-r2)
(28/74) Installing python3-pyc (3.11.3-r11)
(29/74) Installing py3-asn1crypto (1.5.1-r2)
(30/74) Installing py3-cparser (2.21-r2)
(31/74) Installing py3-cparser-pyc (2.21-r2)
(32/74) Installing py3-cffi (1.15.1-r3)
(33/74) Installing py3-cffi-pyc (1.15.1-r3)
(34/74) Installing py3-cryptography (40.0.2-r1)
(35/74) Installing py3-cryptography-pyc (40.0.2-r1)
(36/74) Installing libquadmath (12.2.1_git20220924-r10)
(37/74) Installing libgfortran (12.2.1_git20220924-r10)
(38/74) Installing openblas (0.3.23-r0)
(39/74) Installing py3-numpy (1.24.3-r0)
(40/74) Installing py3-numpy-pyc (1.24.3-r0)
(41/74) Installing libimagequant (4.2.0-r0)
(42/74) Installing openjpeg (2.5.0-r3)
(43/74) Installing py3-pillow (9.5.0-r1)
(44/74) Installing py3-pillow-pyc (9.5.0-r1)
(45/74) Installing py3-parsing (3.0.9-r2)
(46/74) Installing py3-parsing-pyc (3.0.9-r2)
(47/74) Installing py3-packaging (23.1-r1)
(48/74) Installing py3-packaging-pyc (23.1-r1)
(49/74) Installing py3-setuptools (67.7.2-r0)
(50/74) Installing py3-setuptools-pyc (67.7.2-r0)
(51/74) Installing py3-pip (23.1.2-r0)
(52/74) Installing py3-pip-pyc (23.1.2-r0)
(53/74) Installing py3-pynacl (1.5.0-r4)
(54/74) Installing py3-pynacl-pyc (1.5.0-r4)
(55/74) Installing py3-platformdirs (3.5.0-r0)
(56/74) Installing py3-platformdirs-pyc (3.5.0-r0)
(57/74) Installing py3-certifi (2023.5.7-r0)
(58/74) Installing py3-certifi-pyc (2023.5.7-r0)
(59/74) Installing py3-charset-normalizer (3.1.0-r1)
(60/74) Installing py3-charset-normalizer-pyc (3.1.0-r1)
(61/74) Installing py3-idna (3.4-r4)
(62/74) Installing py3-idna-pyc (3.4-r4)
(63/74) Installing py3-urllib3 (1.26.15-r1)
(64/74) Installing py3-urllib3-pyc (1.26.15-r1)
(65/74) Installing py3-requests (2.31.0-r0)
(66/74) Installing py3-requests-pyc (2.31.0-r0)
(67/74) Installing py3-pooch (1.7.0-r1)
(68/74) Installing py3-pooch-pyc (1.7.0-r1)
(69/74) Installing python3-dev (3.11.3-r11)
(70/74) Installing py3-numpy-f2py (1.24.3-r0)
(71/74) Installing py3-scipy (1.10.1-r2)
(72/74) Installing py3-scipy-pyc (1.10.1-r2)
(73/74) Installing supervisor (4.2.5-r2)
(74/74) Installing supervisor-pyc (4.2.5-r2)
Executing busybox-1.36.0-r9.trigger
OK: 728 MiB in 330 packages
[mod-init] **** Installing all pip packages ****
**** Creating venv ****
Requirement already satisfied: pip in /lsiopy/lib/python3.11/site-packages (22.3.1)
Collecting pip
  Downloading pip-23.1.2-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 5.5 MB/s eta 0:00:00
Collecting wheel
  Downloading wheel-0.40.0-py3-none-any.whl (64 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.5/64.5 kB 100.8 kB/s eta 0:00:00
Requirement already satisfied: setuptools in /lsiopy/lib/python3.11/site-packages (65.5.0)
Collecting setuptools
  Downloading setuptools-67.8.0-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 2.5 MB/s eta 0:00:00
Installing collected packages: wheel, setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 65.5.0
    Uninstalling setuptools-65.5.0:
      Successfully uninstalled setuptools-65.5.0
  Attempting uninstall: pip
    Found existing installation: pip 22.3.1
    Uninstalling pip-22.3.1:
      Successfully uninstalled pip-22.3.1
Successfully installed pip-23.1.2 setuptools-67.8.0 wheel-0.40.0
Looking in links: https://wheel-index.linuxserver.io/alpine-3.18/
Collecting pillow-heif
  Downloading pillow_heif-0.11.1-cp311-cp311-musllinux_1_1_x86_64.whl (7.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 6.6 MB/s eta 0:00:00
Collecting hexhamming
  Downloading hexhamming-2.2.3.tar.gz (15 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting pywavelets
  Downloading https://wheels.linuxserver.io/alpine-3.18/PyWavelets-1.4.1-cp311-cp311-linux_x86_64.whl (7.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 6.1 MB/s eta 0:00:00
Collecting pillow>=8.4.0 (from pillow-heif)
  Downloading Pillow-9.5.0-cp311-cp311-musllinux_1_1_x86_64.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 8.4 MB/s eta 0:00:00
Collecting numpy>=1.17.3 (from pywavelets)
  Downloading https://wheels.linuxserver.io/alpine-3.18/numpy-1.24.3-cp311-cp311-linux_x86_64.whl (25.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.8/25.8 MB 8.1 MB/s eta 0:00:00
Building wheels for collected packages: hexhamming
  Building wheel for hexhamming (setup.py): started
  Building wheel for hexhamming (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'hexhamming' extension
      creating build
      creating build/temp.linux-x86_64-cpython-311
      creating build/temp.linux-x86_64-cpython-311/hexhamming
      gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/lsiopy/include -I/usr/include/python3.11 -c hexhamming/python_hexhamming.cc -o build/temp.linux-x86_64-cpython-311/hexhamming/python_hexhamming.o -march=native
      error: command 'gcc' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hexhamming
  Running setup.py clean for hexhamming
Failed to build hexhamming
ERROR: Could not build wheels for hexhamming, which is required to install pyproject.toml-based projects
[custom-init] No custom files found, skipping...
[ls.io-init] done.
Error: Class "PDO" not found in /config/www/nextcloud/lib/private/DB/Connection.php:156
Stack trace:
#0 /config/www/nextcloud/lib/private/AppConfig.php(415): OC\DB\Connection->getQueryBuilder()
#1 /config/www/nextcloud/lib/private/AppConfig.php(184): OC\AppConfig->loadConfigValues()
#2 /config/www/nextcloud/lib/private/AppConfig.php(374): OC\AppConfig->getApps()
#3 /config/www/nextcloud/lib/private/legacy/OC_App.php(976): OC\AppConfig->getValues()
#4 /config/www/nextcloud/lib/private/Server.php(729): OC_App::getAppVersions()
#5 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\Server->OC\{closure}()
#6 /config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#7 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet()
#8 /config/www/nextcloud/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query()
#9 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query()
#10 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(193): OC\AppFramework\Utility\SimpleContainer->get()
#11 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#12 /config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#13 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet()
#14 /config/www/nextcloud/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query()
#15 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query()
#16 /config/www/nextcloud/lib/private/Server.php(1110): OC\AppFramework\Utility\SimpleContainer->get()
#17 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\Server->OC\{closure}()
#18 /config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#19 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet()
#20 /config/www/nextcloud/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query()
#21 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query()
#22 /config/www/nextcloud/lib/private/Server.php(2065): OC\AppFramework\Utility\SimpleContainer->get()
#23 /config/www/nextcloud/lib/private/Files/View.php(119): OC\Server->getLockingProvider()
#24 /config/www/nextcloud/lib/private/Server.php(464): OC\Files\View->__construct()
#25 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\Server->OC\{closure}()
#26 /config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#27 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet()
#28 /config/www/nextcloud/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query()
#29 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query()
#30 /config/www/nextcloud/lib/private/Server.php(1467): OC\AppFramework\Utility\SimpleContainer->get()
#31 /config/www/nextcloud/lib/base.php(625): OC\Server->boot()
#32 /config/www/nextcloud/lib/base.php(1167): OC::init()
#33 /config/www/nextcloud/cron.php(43): require_once('...')
#34 {main}
Error: Class "PDO" not found in /config/www/nextcloud/lib/private/DB/Connection.php:156
Stack trace:
#0 /config/www/nextcloud/lib/private/AppConfig.php(415): OC\DB\Connection->getQueryBuilder()
#1 /config/www/nextcloud/lib/private/AppConfig.php(184): OC\AppConfig->loadConfigValues()
#2 /config/www/nextcloud/lib/private/AppConfig.php(374): OC\AppConfig->getApps()
#3 /config/www/nextcloud/lib/private/legacy/OC_App.php(976): OC\AppConfig->getValues()
#4 /config/www/nextcloud/lib/private/Server.php(729): OC_App::getAppVersions()
#5 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\Server->OC\{closure}()
#6 /config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#7 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet()
#8 /config/www/nextcloud/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query()
#9 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query()
#10 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(193): OC\AppFramework\Utility\SimpleContainer->get()
#11 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#12 /config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#13 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet()
#14 /config/www/nextcloud/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query()
#15 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query()
#16 /config/www/nextcloud/lib/private/Server.php(1110): OC\AppFramework\Utility\SimpleContainer->get()
#17 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\Server->OC\{closure}()
#18 /config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#19 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet()
#20 /config/www/nextcloud/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query()
#21 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query()
#22 /config/www/nextcloud/lib/private/Server.php(2065): OC\AppFramework\Utility\SimpleContainer->get()
#23 /config/www/nextcloud/lib/private/Files/View.php(119): OC\Server->getLockingProvider()
#24 /config/www/nextcloud/lib/private/Server.php(464): OC\Files\View->__construct()
#25 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\Server->OC\{closure}()
#26 /config/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#27 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet()
#28 /config/www/nextcloud/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query()
#29 /config/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query()
#30 /config/www/nextcloud/lib/private/Server.php(1467): OC\AppFramework\Utility\SimpleContainer->get()
#31 /config/www/nextcloud/lib/base.php(625): OC\Server->boot()
#32 /config/www/nextcloud/lib/base.php(1167): OC::init()
#33 /config/www/nextcloud/cron.php(43): require_once('...')
#34 {main}
```

**Comment by j0nnymoe** [comment]
Have you looked to check your mariadb database is working correctly?

**Comment by bsasealteam6** [comment]
No, what should I do for that?

**Comment by j0nnymoe** [comment]
Check the container logs for it.

**Comment by bsasealteam6** [comment]
I recreated the DB container and it fixed the issue loading the page.  However, the updater still doesn't work

**Comment by bsasealteam6** [comment]
I was getting a log from the DB container: 
```
2023-05-20  5:17:56 16283 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255).
2023-05-20  5:17:56 16283 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB').
```
However, that error has been happening for longer than I have been encountering errors

**Comment by bsasealteam6** [comment]
`occ app:update --all` is also still erroring out

**Comment by j0nnymoe** [comment]
Likely need to restore a backup as where you've thought that nextcloud was the issue, it was actually your mariadb instance and running the updates could've broken things.

**Comment by j0nnymoe** [comment]
There has been a breaking change which mariadb released and we've posted info about it here https://info.linuxserver.io/issues/2023-05-29-mariadb/

**Comment by bsasealteam6** [comment]
Running the `mariadb-upgrade` command fixed the MariaDB errors, but I am still both of the other issues with commands

**Comment by bsasealteam6** [comment]
Still haven't managed to get `occ app:update --all` to work

**Comment by bsasealteam6** [comment]
If I run `apk add php81-pdo php81-pdo_mysql php81-posix` it changes to 
```
OCP\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)
```

**Comment by j0nnymoe** [comment]
And for what it's worth, the container already has posix installed. https://github.com/linuxserver/docker-nextcloud/blob/master/package_versions.txt#L210

Considering you're for some reason installing php81 is likely breaking it.

**Comment by bsasealteam6** [comment]
I was installing php81 becaues php -v was returning 8.1.  If you look at the commit details from the bot this morning (https://github.com/linuxserver/docker-nextcloud/commit/c07466d60a3c8907f25fccfae31d6cf991138ade), it updated to php 8.2 this morning (since I submitted the ticket).  It does look like php81-posix was on the install list from yesterday, so I don't know why it didn't get installed, but considering `apk add php81-posix` fixed the issue, something must have gone wrong there.  Also, I got the `occ app:update --all` from Nextcloud's website to update the apps, which is something that should work.  Do you have a better way for me to update the apps?

**Comment by bsasealteam6** [comment]
`updater.phar` is working correctly now though

**Comment by bsasealteam6** [comment]
Also, now that I do further testing, anything with the `occ` app is broken

**Comment by bsasealteam6** [comment]
Figured it out.  One of my package installs was breaking it
