### ISSUE TITLE
[BUG] Cant create administrator account on setup

### ISSUE THREAD

**Issue by TigerdieKatze** [linuxserver/docker-nextcloud#320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I create a new Container based on docker compose I cant create a Admin account on first setup cause of this error: 

> Error while trying to initialise the database: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 8 attempt to write a readonly database

### Expected Behavior

I should be able to create a administrator account on first setup

### Steps To Reproduce

1. Setup Ubuntu Server
2. Install docker and docker compose plugin
3. Start Container per docker compose
4. Try setup

### Environment

```markdown
- OS: Ubuntu Server 22.04
- How docker service was installed: Docker compose
```

### CPU architecture

x86-64

### Docker creation

```bash
---
version: "2.1"---
version: "2.1"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /home/my-user/nextcloud/appdata:/config
      - /hopme/my-user/nextcloud/data:/data
    ports:
      - 8443:443
    restart: unless-stopped
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /home/my-user/nextcloud/appdata:/config
      - /hopme/my-user/nextcloud/data:/data
    ports:
      - 8443:443
    restart: unless-stopped
```
```


### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: executing...
[migrations] 01-nginx-site-confs-default: succeeded
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

Setting resolver to  127.0.0.11
Setting worker_processes to 4
generating self-signed keys in /config/keys, you can replace these with your own keys if required
.........+++++++++++++++++++++++++++++++++++++++*......+............+..+.+..+++++++++++++++++++++++++++++++++++++++*..............+....+.....+............+....+......+..+...+......................+...+...+......+..............+.......+..+.+.....+....+......+......+......+..+.+..............+.......+.....+.+.....+............+.+.........+..+........................+.......+...+.....+......+...+...+...+......+.+........+...................+.....+.......+.....+....+..+....+.........+..+....+.........+.....+.+.....+...+..........+...+..+...+...+.......+.....+.............+......+........+.+.....+.+.........+..+....+......+...++++++
.+......+...+++++++++++++++++++++++++++++++++++++++*.+......+..+++++++++++++++++++++++++++++++++++++++*.......+......+.+..................+..+......+...+.......+...+..+....+.....+...+.+......+...+......+.........+..+.+...+...........+.+........+............+.........+....+..+.........+.+.........+........+...+.................................+.+......+........+.+.....+.........+.......+...+..............+...+.......+.....+.............+........+..........+......+.........+...........+...+...+....+.....+....+.........+..+...+...+.......+............+.........+......+.....+.+.........+......+..+.+..+............+......+.......+........+.........+.......+........+...+....+..............+....+......+.....+.........+...+.......+.....+......+..........+..+.......+..+.+..............+.............+...++++++
-----
# do daily/weekly/monthly maintenance
# min   hour    day     month   weekday command
*/15    *       *       *       *       run-parts /etc/periodic/15min
0       *       *       *       *       run-parts /etc/periodic/hourly
0       2       *       *       *       run-parts /etc/periodic/daily
0       3       *       *       6       run-parts /etc/periodic/weekly
0       5       1       *       *       run-parts /etc/periodic/monthly
# nextcloud cron
*/5     *       *       *       *       s6-setuidgid abc php -f /config/www/nextcloud/cron.php
cp: not replacing '/config/crontabs/root'
[custom-init] No custom files found, skipping...
[ls.io-init] done.
{"reqId":"QIfF305iJC7XBuJbDFeV","level":3,"time":"2023-06-16T23:40:00+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Not installed","userAgent":"--","version":"27.0.0.8","exception":{"Exception":"Exception","Message":"Not installed","Code":0,"Trace":[{"file":"/config/www/nextcloud/lib/base.php","line":705,"function":"checkInstalled","class":"OC","type":"::"},{"file":"/config/www/nextcloud/lib/base.php","line":1173,"function":"init","class":"OC","type":"::"},{"file":"/config/www/nextcloud/cron.php","line":43,"args":["/config/www/nextcloud/lib/base.php"],"function":"require_once"}],"File":"/config/www/nextcloud/lib/base.php","Line":285,"CustomMessage":"--"}}
Exception: Not installed in /config/www/nextcloud/lib/base.php:285
Stack trace:
#0 /config/www/nextcloud/lib/base.php(705): OC::checkInstalled()
#1 /config/www/nextcloud/lib/base.php(1173): OC::init()
#2 /config/www/nextcloud/cron.php(43): require_once('...')
#3 {main}
```

**Comment by aptalca** [comment]
`/hopme` is likely the issue

**Comment by TigerdieKatze** [comment]
Yeah, that fixed it, im just dumb
