### ISSUE TITLE
[BUG] Media not showing in preview in File App

### ISSUE THREAD

**Issue by themitichris** [linuxserver/docker-nextcloud#414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After doing backup of config, data and db (borgmatic) and restoring in a new machine with same docker configuration, media won't show in preview. I can see them if I try to download or in Photos app.
In console I see this error 
`Viewer.vue:639 Could not open file /path/to/file.jpg TypeError: Cannot destructure property 'filename' of 'e' as it is undefined.
    at G (fileUtils.ts:88:23)
    at new K (file.js:35:12)
    at o.openFileInfo (Viewer.vue:725:1)
    at async o.openFile (Viewer.vue:631:1)`

![image](https://github.com/linuxserver/docker-nextcloud/assets/108054911/1efffb40-d631-46f1-93fd-b8f765e65dd6)
![image](https://github.com/linuxserver/docker-nextcloud/assets/108054911/481ae66c-5a2c-4b03-aa5c-a6d4caff4ba0)

### Steps To Reproduce

Docker container 28.0.2-ls300 (latest)
Restore backup (data/config folder, mariadb)
All occ:maintenance commands to fix everything
Open a file from the App Files

### Environment

```markdown
- OS: Proxmox VM debian12, portainer
```

### CPU architecture

x86-64

### Docker creation

```bash
services:
  nextcloud:
    container_name: nextcloud
    image: lscr.io/linuxserver/nextcloud:latest
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_NAME}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
    ports:
      - '8080:80'
      - '443:443'
    links:
      - db
    depends_on:
      - db
    volumes:
      - ${NEXTCLOUD_CONFIG_PATH_EXT}:${NEXTCLOUD_CONFIG_PATH_INT}
      - ${NEXTCLOUD_DATA_PATH_EXT}:${NEXTCLOUD_DATA_PATH_INT}
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
usermod: no changes
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    911
User GID:    911
───────────────────────────────────────
using keys found in /config/keys
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│ 2022-08-16 │ 2023-04-13 │ /config/nginx/nginx.conf                                               │
│ 2022-08-20 │ 2023-08-13 │ /config/nginx/ssl.conf                                                 │
│ 2022-08-20 │ 2024-01-03 │ /config/nginx/site-confs/default.conf                                  │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by themitichris** [comment]
Update, same behaviour after update the original container from 27 to latest 28

**Comment by homerr** [comment]
You need to have the PUID and PGID variables set to allow the container to work correctly. I've just done a test run of this container (on Debian) with no issues.
