### ISSUE TITLE
[BUG] Nexcloud web-install results in "504 Gateway Time-out"

### ISSUE THREAD

**Issue by ceceba223** [linuxserver/docker-nextcloud#415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to set up the official linuxserver.io nexcloud image (first through portainer but I also tried CLI). The container deploys successfully and I can access the web setup. I enter admin username and password and click install, the server then loads for a while before displaying `504 Gateway Time-out`. At the same time the docker log displays the following error:

```
Exception: Not installed in /app/www/public/lib/base.php:283
Stack trace:
#0 /app/www/public/lib/base.php(709): OC::checkInstalled()
#1 /app/www/public/lib/base.php(1200): OC::init()
#2 /app/www/public/cron.php(43): require_once('...')
#3 {main}
```

### Expected Behavior

The Web setup finishes loading and creates an admin user from which i can user nextcloud.

### Steps To Reproduce

1. Run Debian GNU/Linux 12 (bookworm) (inside Proxmox)
2. Run the CLI command from the linuxserver.io docs
3. Access the webpage
4. Enter Username and password & click install
5. `504 Gateway Time-out`

### Environment

```markdown
- OS: Debian GNU/Linux 12 (bookworm) (inside Proxmox 8)
- How docker service was installed: Docker version 25.0.3
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run -d \
  --name=nextcloud \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/Berlin \
  -p 443:443 \
  -v /home/prox-deb/docker/config/nextcloud:/config \
  -v /mnt/true-nas-share/media/docker/nextcloud:/data \
  --restart unless-stopped \
  lscr.io/linuxserver/nextcloud:latest
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

using keys found in /config/keys
Initializing nextcloud 28.0.2.5 (this can take a while) ...
Setting permissions
New nextcloud instance
Please run the web-based installer on first connect!
Initializing finished
After completing the web-based installer, restart the Nextcloud container to apply default memory caching and transactional file locking configurations.
Alternatively, you can apply your own configurations by editing /config/www/nextcloud/config/config.php following the documentation:
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/caching_configuration.html
https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/files_locking_transactional.html
[custom-init] No custom files found, skipping...
[ls.io-init] done.
Exception: Not installed in /app/www/public/lib/base.php:283
Stack trace:
#0 /app/www/public/lib/base.php(709): OC::checkInstalled()
#1 /app/www/public/lib/base.php(1200): OC::init()
#2 /app/www/public/cron.php(43): require_once('...')
#3 {main}
Exception: Not installed in /app/www/public/lib/base.php:283
Stack trace:
#0 /app/www/public/lib/base.php(709): OC::checkInstalled()
#1 /app/www/public/lib/base.php(1200): OC::init()
#2 /app/www/public/cron.php(43): require_once('...')
#3 {main}
Exception: Not installed in /app/www/public/lib/base.php:283
Stack trace:
#0 /app/www/public/lib/base.php(709): OC::checkInstalled()
#1 /app/www/public/lib/base.php(1200): OC::init()
#2 /app/www/public/cron.php(43): require_once('...')
#3 {main}
Exception: Not installed in /app/www/public/lib/base.php:283
Stack trace:
#0 /app/www/public/lib/base.php(709): OC::checkInstalled()
#1 /app/www/public/lib/base.php(1200): OC::init()
#2 /app/www/public/cron.php(43): require_once('...')
#3 {main}
```

**Comment by ceceba223** [comment]
My issue seems to be really similar to issue #280 . but I'm not using a autoconfig.php file to skip the web setup (which is whats causing the issue on github if I understand it correctly)

**Comment by homerr** [comment]
Issue was related to versions prior to 28.0.3 - closing.
