### ISSUE TITLE
Unable to Update Next Cloud to version 29.0.2.2 (Unraid - Docker)

### ISSUE THREAD

**Issue by schalmers617** [linuxserver/docker-nextcloud#442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

using keys found in /config/keys
Initializing nextcloud 29.0.2.2 (this can take a while) ...
Upgrading nextcloud from 29.0.1.1 ...
Setting permissions
An unhandled exception has been thrown:
Error: Failed opening required '/config/www/nextcloud/apps/mail/vendor/composer/../symfony/polyfill-iconv/bootstrap.php' (include_path='/app/www/public/3rdparty/pear/archive_tar:/app/www/public/3rdparty/pear/console_getopt:/app/www/public/3rdparty/pear/pear-core-minimal/src:/app/www/public/3rdparty/pear/pear_exception:/app/www/public/apps') in /config/www/nextcloud/apps/mail/vendor/composer/autoload_real.php:41

### Expected Behavior

Should be able to upgrade

### Steps To Reproduce

Upgrade from version 29.0.1.1 to 29.0.2.2

### Environment

```markdown
- OS: UNRAID 6.12.9
- How docker service was installed:  was preinstalled in Unraid
```

### CPU architecture

x86-64

### Docker creation

```bash
used Docker templates from Unraid
```

### Container logs

```bash
root@HomeSrv:~# docker logs nextcloud
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

using keys found in /config/keys
Initializing nextcloud 29.0.2.2 (this can take a while) ...
Upgrading nextcloud from 29.0.1.1 ...
Setting permissions
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Update app calendar from App Store
Update app mail from App Store
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

using keys found in /config/keys
Initializing nextcloud 29.0.2.2 (this can take a while) ...
Upgrading nextcloud from 29.0.1.1 ...
Setting permissions
An unhandled exception has been thrown:
Error: Failed opening required '/config/www/nextcloud/apps/mail/vendor/composer/../symfony/polyfill-iconv/bootstrap.php' (include_path='/app/www/public/3rdparty/pear/archive_tar:/app/www/public/3rdparty/pear/console_getopt:/app/www/public/3rdparty/pear/pear-core-minimal/src:/app/www/public/3rdparty/pear/pear_exception:/app/www/public/apps') in /config/www/nextcloud/apps/mail/vendor/composer/autoload_real.php:41
Stack trace:
#0 /config/www/nextcloud/apps/mail/vendor/composer/autoload_real.php(45): {closure}()
#1 /config/www/nextcloud/apps/mail/vendor/autoload.php(25): ComposerAutoloaderInitMail::getLoader()
#2 /config/www/nextcloud/apps/mail/composer/autoload.php(5): require_once('...')
#3 /app/www/public/lib/private/legacy/OC_App.php(161): require_once('...')
#4 /app/www/public/lib/private/AppFramework/Bootstrap/Coordinator.php(119): OC_App::registerAutoloading()
#5 /app/www/public/lib/private/AppFramework/Bootstrap/Coordinator.php(90): OC\AppFramework\Bootstrap\Coordinator->registerApps()
#6 /app/www/public/lib/base.php(706): OC\AppFramework\Bootstrap\Coordinator->runInitialRegistration()
#7 /app/www/public/lib/base.php(1181): OC::init()
#8 /app/www/public/console.php(48): require_once('...')
#9 /app/www/public/occ(11): require_once('...')
#10 {main}Initializing finished
After completing the web-based installer, restart the Nextcloud container to apply default memory caching and transactional file locking configurations.
Alternatively, you can apply your own configurations by editing /config/www/nextcloud/config/config.php following the documentation:
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/caching_configuration.html
https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/files_locking_transactional.html
[custom-init] No custom files found, skipping...
[ls.io-init] done.
Error: Failed opening required '/config/www/nextcloud/apps/mail/vendor/composer/../symfony/polyfill-iconv/bootstrap.php' (include_path='/app/www/public/3rdparty/pear/archive_tar:/app/www/public/3rdparty/pear/console_getopt:/app/www/public/3rdparty/pear/pear-core-minimal/src:/app/www/public/3rdparty/pear/pear_exception:/app/www/public/apps') in /config/www/nextcloud/apps/mail/vendor/composer/autoload_real.php:41
Stack trace:
#0 /config/www/nextcloud/apps/mail/vendor/composer/autoload_real.php(45): {closure}()
#1 /config/www/nextcloud/apps/mail/vendor/autoload.php(25): ComposerAutoloaderInitMail::getLoader()
#2 /config/www/nextcloud/apps/mail/composer/autoload.php(5): require_once('...')
#3 /app/www/public/lib/private/legacy/OC_App.php(161): require_once('...')
#4 /app/www/public/lib/private/AppFramework/Bootstrap/Coordinator.php(119): OC_App::registerAutoloading()
#5 /app/www/public/lib/private/AppFramework/Bootstrap/Coordinator.php(90): OC\AppFramework\Bootstrap\Coordinator->registerApps()
#6 /app/www/public/lib/base.php(706): OC\AppFramework\Bootstrap\Coordinator->runInitialRegistration()
#7 /app/www/public/lib/base.php(1181): OC::init()
#8 /app/www/public/cron.php(58): require_once('...')
#9 {main}
Error: Failed opening required '/config/www/nextcloud/apps/mail/vendor/composer/../symfony/polyfill-iconv/bootstrap.php' (include_path='/app/www/public/3rdparty/pear/archive_tar:/app/www/public/3rdparty/pear/console_getopt:/app/www/public/3rdparty/pear/pear-core-minimal/src:/app/www/public/3rdparty/pear/pear_exception:/app/www/public/apps') in /config/www/nextcloud/apps/mail/vendor/composer/autoload_real.php:41
Stack trace:
#0 /config/www/nextcloud/apps/mail/vendor/composer/autoload_real.php(45): {closure}()
#1 /config/www/nextcloud/apps/mail/vendor/autoload.php(25): ComposerAutoloaderInitMail::getLoader()
#2 /config/www/nextcloud/apps/mail/composer/autoload.php(5): require_once('...')
#3 /app/www/public/lib/private/legacy/OC_App.php(161): require_once('...')
#4 /app/www/public/lib/private/AppFramework/Bootstrap/Coordinator.php(119): OC_App::registerAutoloading()
#5 /app/www/public/lib/private/AppFramework/Bootstrap/Coordinator.php(90): OC\AppFramework\Bootstrap\Coordinator->registerApps()
#6 /app/www/public/lib/base.php(706): OC\AppFramework\Bootstrap\Coordinator->runInitialRegistration()
#7 /app/www/public/lib/base.php(1181): OC::init()
#8 /app/www/public/cron.php(58): require_once('...')
#9 {main}
Error: Failed opening required '/config/www/nextcloud/apps/mail/vendor/composer/../symfony/polyfill-iconv/bootstrap.php' (include_path='/app/www/public/3rdparty/pear/archive_tar:/app/www/public/3rdparty/pear/console_getopt:/app/www/public/3rdparty/pear/pear-core-minimal/src:/app/www/public/3rdparty/pear/pear_exception:/app/www/public/apps') in /config/www/nextcloud/apps/mail/vendor/composer/autoload_real.php:41
Stack trace:
#0 /config/www/nextcloud/apps/mail/vendor/composer/autoload_real.php(45): {closure}()
#1 /config/www/nextcloud/apps/mail/vendor/autoload.php(25): ComposerAutoloaderInitMail::getLoader()
#2 /config/www/nextcloud/apps/mail/composer/autoload.php(5): require_once('...')
#3 /app/www/public/lib/private/legacy/OC_App.php(161): require_once('...')
#4 /app/www/public/lib/private/AppFramework/Bootstrap/Coordinator.php(119): OC_App::registerAutoloading()
#5 /app/www/public/lib/private/AppFramework/Bootstrap/Coordinator.php(90): OC\AppFramework\Bootstrap\Coordinator->registerApps()
#6 /app/www/public/lib/base.php(706): OC\AppFramework\Bootstrap\Coordinator->runInitialRegistration()
#7 /app/www/public/lib/base.php(1181): OC::init()
#8 /app/www/public/cron.php(58): require_once('...')
#9 {main}
Error: Failed opening required '/config/www/nextcloud/apps/mail/vendor/composer/../symfony/polyfill-iconv/bootstrap.php' (include_path='/app/www/public/3rdparty/pear/archive_tar:/app/www/public/3rdparty/pear/console_getopt:/app/www/public/3rdparty/pear/pear-core-minimal/src:/app/www/public/3rdparty/pear/pear_exception:/app/www/public/apps') in /config/www/nextcloud/apps/mail/vendor/composer/autoload_real.php:41
Stack trace:
#0 /config/www/nextcloud/apps/mail/vendor/composer/autoload_real.php(45): {closure}()
#1 /config/www/nextcloud/apps/mail/vendor/autoload.php(25): ComposerAutoloaderInitMail::getLoader()
#2 /config/www/nextcloud/apps/mail/composer/autoload.php(5): require_once('...')
#3 /app/www/public/lib/private/legacy/OC_App.php(161): require_once('...')
#4 /app/www/public/lib/private/AppFramework/Bootstrap/Coordinator.php(119): OC_App::registerAutoloading()
#5 /app/www/public/lib/private/AppFramework/Bootstrap/Coordinator.php(90): OC\AppFramework\Bootstrap\Coordinator->registerApps()
#6 /app/www/public/lib/base.php(706): OC\AppFramework\Bootstrap\Coordinator->runInitialRegistration()
#7 /app/www/public/lib/base.php(1181): OC::init()
#8 /app/www/public/cron.php(58): require_once('...')
#9 {main}
Error: Failed opening required '/config/www/nextcloud/apps/mail/vendor/composer/../symfony/polyfill-iconv/bootstrap.php' (include_path='/app/www/public/3rdparty/pear/archive_tar:/app/www/public/3rdparty/pear/console_getopt:/app/www/public/3rdparty/pear/pear-core-minimal/src:/app/www/public/3rdparty/pear/pear_exception:/app/www/public/apps') in /config/www/nextcloud/apps/mail/vendor/composer/autoload_real.php:41
Stack trace:
#0 /config/www/nextcloud/apps/mail/vendor/composer/autoload_real.php(45): {closure}()
#1 /config/www/nextcloud/apps/mail/vendor/autoload.php(25): ComposerAutoloaderInitMail::getLoader()
#2 /config/www/nextcloud/apps/mail/composer/autoload.php(5): require_once('...')
#3 /app/www/public/lib/private/legacy/OC_App.php(161): require_once('...')
#4 /app/www/public/lib/private/AppFramework/Bootstrap/Coordinator.php(119): OC_App::registerAutoloading()
#5 /app/www/public/lib/private/AppFramework/Bootstrap/Coordinator.php(90): OC\AppFramework\Bootstrap\Coordinator->registerApps()
#6 /app/www/public/lib/base.php(706): OC\AppFramework\Bootstrap\Coordinator->runInitialRegistration()
#7 /app/www/public/lib/base.php(1181): OC::init()
#8 /app/www/public/cron.php(58): require_once('...')
#9 {main}
Error: Failed opening required '/config/www/nextcloud/apps/mail/vendor/composer/../symfony/polyfill-iconv/bootstrap.php' (include_path='/app/www/public/3rdparty/pear/archive_tar:/app/www/public/3rdparty/pear/console_getopt:/app/www/public/3rdparty/pear/pear-core-minimal/src:/app/www/public/3rdparty/pear/pear_exception:/app/www/public/apps') in /config/www/nextcloud/apps/mail/vendor/composer/autoload_real.php:41
Stack trace:
#0 /config/www/nextcloud/apps/mail/vendor/composer/autoload_real.php(45): {closure}()
#1 /config/www/nextcloud/apps/mail/vendor/autoload.php(25): ComposerAutoloaderInitMail::getLoader()
#2 /config/www/nextcloud/apps/mail/composer/autoload.php(5): require_once('...')
#3 /app/www/public/lib/private/legacy/OC_App.php(161): require_once('...')
#4 /app/www/public/lib/private/AppFramework/Bootstrap/Coordinator.php(119): OC_App::registerAutoloading()
#5 /app/www/public/lib/private/AppFramework/Bootstrap/Coordinator.php(90): OC\AppFramework\Bootstrap\Coordinator->registerApps()
#6 /app/www/public/lib/base.php(706): OC\AppFramework\Bootstrap\Coordinator->runInitialRegistration()
#7 /app/www/public/lib/base.php(1181): OC::init()
#8 /app/www/public/cron.php(58): require_once('...')
#9 {main}
Error: Failed opening required '/config/www/nextcloud/apps/mail/vendor/composer/../symfony/polyfill-iconv/bootstrap.php' (include_path='/app/www/public/3rdparty/pear/archive_tar:/app/www/public/3rdparty/pear/console_getopt:/app/www/public/3rdparty/pear/pear-core-minimal/src:/app/www/public/3rdparty/pear/pear_exception:/app/www/public/apps') in /config/www/nextcloud/apps/mail/vendor/composer/autoload_real.php:41
Stack trace:
#0 /config/www/nextcloud/apps/mail/vendor/composer/autoload_real.php(45): {closure}()
#1 /config/www/nextcloud/apps/mail/vendor/autoload.php(25): ComposerAutoloaderInitMail::getLoader()
#2 /config/www/nextcloud/apps/mail/composer/autoload.php(5): require_once('...')
#3 /app/www/public/lib/private/legacy/OC_App.php(161): require_once('...')
#4 /app/www/public/lib/private/AppFramework/Bootstrap/Coordinator.php(119): OC_App::registerAutoloading()
#5 /app/www/public/lib/private/AppFramework/Bootstrap/Coordinator.php(90): OC\AppFramework\Bootstrap\Coordinator->registerApps()
#6 /app/www/public/lib/base.php(706): OC\AppFramework\Bootstrap\Coordinator->runInitialRegistration()
#7 /app/www/public/lib/base.php(1181): OC::init()
#8 /app/www/public/cron.php(58): require_once('...')
#9 {main}
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

using keys found in /config/keys
Initializing nextcloud 29.0.2.2 (this can take a while) ...
Upgrading nextcloud from 29.0.1.1 ...
Setting permissions
An unhandled exception has been thrown:
Error: Failed opening required '/config/www/nextcloud/apps/mail/vendor/composer/../symfony/polyfill-iconv/bootstrap.php' (include_path='/app/www/public/3rdparty/pear/archive_tar:/app/www/public/3rdparty/pear/console_getopt:/app/www/public/3rdparty/pear/pear-core-minimal/src:/app/www/public/3rdparty/pear/pear_exception:/app/www/public/apps') in /config/www/nextcloud/apps/mail/vendor/composer/autoload_real.php:41
Stack trace:
#0 /config/www/nextcloud/apps/mail/vendor/composer/autoload_real.php(45): {closure}()
#1 /config/www/nextcloud/apps/mail/vendor/autoload.php(25): ComposerAutoloaderInitMail::getLoader()
#2 /config/www/nextcloud/apps/mail/composer/autoload.php(5): require_once('...')
#3 /app/www/public/lib/private/legacy/OC_App.php(161): require_once('...')
#4 /app/www/public/lib/private/AppFramework/Bootstrap/Coordinator.php(119): OC_App::registerAutoloading()
#5 /app/www/public/lib/private/AppFramework/Bootstrap/Coordinator.php(90): OC\AppFramework\Bootstrap\Coordinator->registerApps()
#6 /app/www/public/lib/base.php(706): OC\AppFramework\Bootstrap\Coordinator->runInitialRegistration()
#7 /app/www/public/lib/base.php(1181): OC::init()
#8 /app/www/public/console.php(48): require_once('...')
#9 /app/www/public/occ(11): require_once('...')
#10 {main}Initializing finished
After completing the web-based installer, restart the Nextcloud container to apply default memory caching and transactional file locking configurations.
Alternatively, you can apply your own configurations by editing /config/www/nextcloud/config/config.php following the documentation:
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/caching_configuration.html
https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/files_locking_transactional.html
[custom-init] No custom files found, skipping...
[ls.io-init] done.
Error: Failed opening required '/config/www/nextcloud/apps/mail/vendor/composer/../symfony/polyfill-iconv/bootstrap.php' (include_path='/app/www/public/3rdparty/pear/archive_tar:/app/www/public/3rdparty/pear/console_getopt:/app/www/public/3rdparty/pear/pear-core-minimal/src:/app/www/public/3rdparty/pear/pear_exception:/app/www/public/apps') in /config/www/nextcloud/apps/mail/vendor/composer/autoload_real.php:41
Stack trace:
#0 /config/www/nextcloud/apps/mail/vendor/composer/autoload_real.php(45): {closure}()
#1 /config/www/nextcloud/apps/mail/vendor/autoload.php(25): ComposerAutoloaderInitMail::getLoader()
#2 /config/www/nextcloud/apps/mail/composer/autoload.php(5): require_once('...')
#3 /app/www/public/lib/private/legacy/OC_App.php(161): require_once('...')
#4 /app/www/public/lib/private/AppFramework/Bootstrap/Coordinator.php(119): OC_App::registerAutoloading()
#5 /app/www/public/lib/private/AppFramework/Bootstrap/Coordinator.php(90): OC\AppFramework\Bootstrap\Coordinator->registerApps()
#6 /app/www/public/lib/base.php(706): OC\AppFramework\Bootstrap\Coordinator->runInitialRegistration()
#7 /app/www/public/lib/base.php(1181): OC::init()
#8 /app/www/public/cron.php(58): require_once('...')
#9 {main}
Error: Failed opening required '/config/www/nextcloud/apps/mail/vendor/composer/../symfony/polyfill-iconv/bootstrap.php' (include_path='/app/www/public/3rdparty/pear/archive_tar:/app/www/public/3rdparty/pear/console_getopt:/app/www/public/3rdparty/pear/pear-core-minimal/src:/app/www/public/3rdparty/pear/pear_exception:/app/www/public/apps') in /config/www/nextcloud/apps/mail/vendor/composer/autoload_real.php:41
Stack trace:
#0 /config/www/nextcloud/apps/mail/vendor/composer/autoload_real.php(45): {closure}()
#1 /config/www/nextcloud/apps/mail/vendor/autoload.php(25): ComposerAutoloaderInitMail::getLoader()
#2 /config/www/nextcloud/apps/mail/composer/autoload.php(5): require_once('...')
#3 /app/www/public/lib/private/legacy/OC_App.php(161): require_once('...')
#4 /app/www/public/lib/private/AppFramework/Bootstrap/Coordinator.php(119): OC_App::registerAutoloading()
#5 /app/www/public/lib/private/AppFramework/Bootstrap/Coordinator.php(90): OC\AppFramework\Bootstrap\Coordinator->registerApps()
#6 /app/www/public/lib/base.php(706): OC\AppFramework\Bootstrap\Coordinator->runInitialRegistration()
#7 /app/www/public/lib/base.php(1181): OC::init()
#8 /app/www/public/cron.php(58): require_once('...')
#9 {main}
root@HomeSrv:~#
```

**Comment by arkharim** [comment]
Hi,

I solved with the following steps:

1. Use the occ command to update the nextcloud version.
2. Use occ command to update all apps.
3. Some apps cannot activate anymore. I deleted them from the /config/www/nextcloud/apps folder
4. Reinstall them as normal.

The only reaming point to be fixed is an error with the server configuration with: /.well-known/caldav :(

**Comment by cotrain22** [comment]
I just tried to install nextcloud on unraid. I looked at the logs and this is the message I got. is there a fix for this?
![Screenshot (13)](https://github.com/linuxserver/docker-nextcloud/assets/122317033/6dc74acf-364a-42fb-890d-dd1fe539110f)
Thanks
