### ISSUE TITLE
[BUG] New install, Can't Connect

### ISSUE THREAD

**Issue by F1zzyD** [linuxserver/docker-nextcloud#443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Ran `docker compose up` and the logs finish with "[ls.io--init] done. Tried to access with the default port and not messing with anything except for the volumes set to `./config:/config` etc. I get the webpage "Unable to Connect".

### Expected Behavior

I should be able to connect?

### Steps To Reproduce

run `docker compose up` and access `localhost:443`.

### Environment

```markdown
- OS: Linux Mint
- How docker service was installed: using compose.yml
```

### CPU architecture

x86-64

### Docker creation

```bash
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - ./data:/data
    ports:
      - 443:443
    restart: unless-stopped
```

### Container logs

```bash
✔ Container nextcloud  Created                                                                                  0.0s 
Attaching to nextcloud
nextcloud  | [migrations] started
nextcloud  | [migrations] 01-nginx-site-confs-default: executing...
nextcloud  | [migrations] 01-nginx-site-confs-default: succeeded
nextcloud  | [migrations] 02-default-location: executing...
nextcloud  | [migrations] 02-default-location: succeeded
nextcloud  | [migrations] done
nextcloud  | ───────────────────────────────────────
nextcloud  | 
nextcloud  |       ██╗     ███████╗██╗ ██████╗
nextcloud  |       ██║     ██╔════╝██║██╔═══██╗
nextcloud  |       ██║     ███████╗██║██║   ██║
nextcloud  |       ██║     ╚════██║██║██║   ██║
nextcloud  |       ███████╗███████║██║╚██████╔╝
nextcloud  |       ╚══════╝╚══════╝╚═╝ ╚═════╝
nextcloud  | 
nextcloud  |    Brought to you by linuxserver.io
nextcloud  | ───────────────────────────────────────
nextcloud  | 
nextcloud  | To support LSIO projects visit:
nextcloud  | https://www.linuxserver.io/donate/
nextcloud  | 
nextcloud  | ───────────────────────────────────────
nextcloud  | GID/UID
nextcloud  | ───────────────────────────────────────
nextcloud  | 
nextcloud  | User UID:    1000
nextcloud  | User GID:    1000
nextcloud  | ───────────────────────────────────────
nextcloud  | 
nextcloud  | Setting resolver to  127.0.0.11
nextcloud  | Setting worker_processes to 6
nextcloud  | generating self-signed keys in /config/keys, you can replace these with your own keys if required
nextcloud  | ......+.+........+.+..................+.....+...+...+.+...+..+.+.....+...............+....+.........+..+...+.......+........+.+...+.................+++++++++++++++++++++++++++++++++++++++*.......+...+++++++++++++++++++++++++++++++++++++++*.+....+........+...+....+..+...................+..............+.+.........+......+...........+...+.......+.....+.+..+.+.....+.+......++++++
nextcloud  | ..+....+.....+....+...............+++++++++++++++++++++++++++++++++++++++*.........+...+..+.+++++++++++++++++++++++++++++++++++++++*....+.+......+..............+...+.+.....+......+.+...+..+.........+.............+..+....+.....+......+....+..+....+........+.+..+...................+......+........++++++
nextcloud  | -----
nextcloud  | Initializing nextcloud 29.0.2.2 (this can take a while) ...
nextcloud  | Setting permissions
nextcloud  | New nextcloud instance
nextcloud  | Please run the web-based installer on first connect!
nextcloud  | Initializing finished
nextcloud  | After completing the web-based installer, restart the Nextcloud container to apply default memory caching and transactional file locking configurations.
nextcloud  | Alternatively, you can apply your own configurations by editing /config/www/nextcloud/config/config.php following the documentation:
nextcloud  | https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/caching_configuration.html
nextcloud  | https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/files_locking_transactional.html
nextcloud  | [custom-init] No custom files found, skipping...
nextcloud  | [ls.io-init] done.
nextcloud  | Exception: Not installed in /app/www/public/lib/base.php:284
nextcloud  | Stack trace:
nextcloud  | #0 /app/www/public/lib/base.php(715): OC::checkInstalled()
nextcloud  | #1 /app/www/public/lib/base.php(1181): OC::init()
nextcloud  | #2 /app/www/public/cron.php(58): require_once('...')
nextcloud  | #3 {main}
nextcloud  | Exception: Not installed in /app/www/public/lib/base.php:284
nextcloud  | Stack trace:
nextcloud  | #0 /app/www/public/lib/base.php(715): OC::checkInstalled()
nextcloud  | #1 /app/www/public/lib/base.php(1181): OC::init()
nextcloud  | #2 /app/www/public/cron.php(58): require_once('...')
nextcloud  | #3 {main}
```

**Comment by annie-elequin** [comment]
I have a similar issue, I get 400 bad request when trying to access the page - I think my stack trace is a bit different from yours, but instead of making a new ticket I thought I'd share here since they might be related. 

```
---
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /config:/config
      - /data:/data
    ports:
      - 443:443
    restart: unless-stopped
```

```
Exception: Not installed in /app/www/public/lib/base.php:284

Stack trace:
#0 /app/www/public/lib/base.php(715): OC::checkInstalled()
#1 /app/www/public/lib/base.php(1181): OC::init()
#2 /app/www/public/cron.php(58): require_once('...')

}
```

**Comment by Felix2M** [comment]
@annie-elequin  I get the same error message from nginx. What is weird at my place: I can always connect with my Laptop, but with other devices like my phone or another laptop I get 400 bad request.
Did you solve this issue already?

**Comment by wymchicane** [comment]
I am facing this issue aswell. I can connect to the "Install page", but when creating an admin account I run into a 504 Gateway Time-out. 
My compose.yaml is identical to the one of the previous posters (apart from tz and paths
OS is a debian 12 VM ontop of Proxmox 8.2.2

**Comment by brucekinsey** [comment]
> I am facing this issue aswell. I can connect to the "Install page", but when creating an admin account I run into a 504 Gateway Time-out. My compose.yaml is identical to the one of the previous posters (apart from tz and paths), the traceback is identical OS is a debian 12 VM ontop of Proxmox 8.2.2

I ended up running the following (only tried in v28.0.9 so far):
sudo docker exec -it nextcloud occ maintenance:install --admin-user admin --admin-pass mypassword

Restarted the container after that and it worked. occ maintenance:mode did not work.

**Comment by F1zzyD** [comment]
Update: I ended up giving up and moving to alternative services. Nextcloud is too buggy and lags horribly.
