### ISSUE TITLE
[BUG] Can't Connect To Database Since Upgrade To 30

### ISSUE THREAD

**Issue by uniquePWD** [linuxserver/docker-nextcloud#473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

NextCloud doesn't run any more. Was running perfectly for months. 

### Expected Behavior

NextCloud runs as normal

### Steps To Reproduce

1. Start NextCloud Docker container

### Environment

```markdown
- OS: Raspberry Pi OS
- How docker service was installed: Compose
```

### CPU architecture

arm64

### Docker creation

```bash
Will edit in
```

### Container logs

```bash
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│ 2024-01-03 │ 2024-07-16 │ /config/nginx/site-confs/default.conf                                  │
│ 2023-04-13 │ 2024-05-27 │ /config/nginx/nginx.conf                                               │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
[custom-init] No custom files found, skipping...
[ls.io-init] done.
nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /config/nginx/site-confs/default.conf:13
nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /config/nginx/site-confs/default.conf:14
Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "192.168.0.164", port 4461 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections? in /app/www/public/lib/private/DB/Connection.php:233

Stack trace:
#0 /app/www/public/3rdparty/doctrine/dbal/src/Connection.php(453): OC\DB\Connection->connect()
#1 /app/www/public/3rdparty/doctrine/dbal/src/Connection.php(411): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /app/www/public/3rdparty/doctrine/dbal/src/Connection.php(318): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /app/www/public/3rdparty/doctrine/dbal/src/Connection.php(1320): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /app/www/public/lib/private/DB/Connection.php(191): Doctrine\DBAL\Connection->setNestTransactionsWithSavepoints()
#5 /app/www/public/3rdparty/doctrine/dbal/src/DriverManager.php(197): OC\DB\Connection->__construct()
#6 /app/www/public/lib/private/DB/ConnectionFactory.php(148): Doctrine\DBAL\DriverManager::getConnection()
#7 /app/www/public/lib/private/Server.php(819): OC\DB\ConnectionFactory->getConnection()
#8 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(153): OC\Server->OC\{closure}()
#9 /app/www/public/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#10 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(120): Pimple\Container->offsetGet()
#11 /app/www/public/lib/private/ServerContainer.php(155): OC\AppFramework\Utility\SimpleContainer->query()
#12 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(74): OC\ServerContainer->query()
#13 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#14 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(61): array_map()
#15 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(106): OC\AppFramework\Utility\SimpleContainer->buildClass()
#16 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(124): OC\AppFramework\Utility\SimpleContainer->resolve()
#17 /app/www/public/lib/private/ServerContainer.php(155): OC\AppFramework\Utility\SimpleContainer->query()
#18 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(42): OC\ServerContainer->query()
#19 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(175): OC\AppFramework\Utility\SimpleContainer->get()
#20 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(153): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#21 /app/www/public/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#22 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(120): Pimple\Container->offsetGet()
#23 /app/www/public/lib/private/ServerContainer.php(155): OC\AppFramework\Utility\SimpleContainer->query()
#24 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(74): OC\ServerContainer->query()
#25 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#26 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(61): array_map()
#27 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(106): OC\AppFramework\Utility\SimpleContainer->buildClass()
#28 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(124): OC\AppFramework\Utility\SimpleContainer->resolve()
#29 /app/www/public/lib/private/ServerContainer.php(155): OC\AppFramework\Utility\SimpleContainer->query()
#30 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(74): OC\ServerContainer->query()
#31 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#32 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(61): array_map()
#33 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(106): OC\AppFramework\Utility\SimpleContainer->buildClass()
#34 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(124): OC\AppFramework\Utility\SimpleContainer->resolve()
#35 /app/www/public/lib/private/ServerContainer.php(155): OC\AppFramework\Utility\SimpleContainer->query()
#36 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(74): OC\ServerContainer->query()
#37 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#38 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(61): array_map()
#39 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(106): OC\AppFramework\Utility\SimpleContainer->buildClass()
#40 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(124): OC\AppFramework\Utility\SimpleContainer->resolve()
#41 /app/www/public/lib/private/ServerContainer.php(155): OC\AppFramework\Utility\SimpleContainer->query()
#42 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(42): OC\ServerContainer->query()
#43 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(175): OC\AppFramework\Utility\SimpleContainer->get()
#44 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(153): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#45 /app/www/public/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#46 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(120): Pimple\Container->offsetGet()
#47 /app/www/public/lib/private/ServerContainer.php(155): OC\AppFramework\Utility\SimpleContainer->query()
#48 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(42): OC\ServerContainer->query()
#49 /app/www/public/lib/private/Server.php(497): OC\AppFramework\Utility\SimpleContainer->get()
#50 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(153): OC\Server->OC\{closure}()
#51 /app/www/public/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#52 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(120): Pimple\Container->offsetGet()
#53 /app/www/public/lib/private/ServerContainer.php(155): OC\AppFramework\Utility\SimpleContainer->query()
#54 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(42): OC\ServerContainer->query()
#55 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(175): OC\AppFramework\Utility\SimpleContainer->get()
#56 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(153): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#57 /app/www/public/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#58 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(120): Pimple\Container->offsetGet()
#59 /app/www/public/lib/private/ServerContainer.php(155): OC\AppFramework\Utility\SimpleContainer->query()
#60 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(42): OC\ServerContainer->query()
#61 /app/www/public/lib/private/Server.php(857): OC\AppFramework\Utility\SimpleContainer->get()
#62 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(153): OC\Server->OC\{closure}()
#63 /app/www/public/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#64 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(120): Pimple\Container->offsetGet()
#65 /app/www/public/lib/private/ServerContainer.php(155): OC\AppFramework\Utility\SimpleContainer->query()
#66 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(42): OC\ServerContainer->query()
#67 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(175): OC\AppFramework\Utility\SimpleContainer->get()
#68 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(153): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#69 /app/www/public/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#70 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(120): Pimple\Container->offsetGet()
#71 /app/www/public/lib/private/ServerContainer.php(155): OC\AppFramework\Utility\SimpleContainer->query()
#72 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(74): OC\ServerContainer->query()
#73 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#74 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(61): array_map()
#75 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(106): OC\AppFramework\Utility\SimpleContainer->buildClass()
#76 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(124): OC\AppFramework\Utility\SimpleContainer->resolve()
#77 /app/www/public/lib/private/ServerContainer.php(155): OC\AppFramework\Utility\SimpleContainer->query()
#78 /app/www/public/lib/private/AppFramework/Utility/SimpleContainer.php(42): OC\ServerContainer->query()
#79 /app/www/public/lib/public/Server.php(39): OC\AppFramework\Utility\SimpleContainer->get()
#80 /app/www/public/lib/base.php(656): OCP\Server::get()
#81 /app/www/public/lib/base.php(1132): OC::init()
#82 /app/www/public/cron.php(24): require_once('...')
#83 {main}
```

**Comment by uniquePWD** [comment]
The database logs say this

```
PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-09-29 15:33:52.279 UTC [1] FATAL:  database files are incompatible with server
2024-09-29 15:33:52.279 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 17.0 (Debian 17.0-1.pgdg120+1).
PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-09-29 15:34:52.694 UTC [1] FATAL:  database files are incompatible with server
2024-09-29 15:34:52.694 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 17.0 (Debian 17.0-1.pgdg120+1).
PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-09-29 15:35:53.244 UTC [1] FATAL:  database files are incompatible with server
2024-09-29 15:35:53.244 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 17.0 (Debian 17.0-1.pgdg120+1).
PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-09-29 15:36:53.673 UTC [1] FATAL:  database files are incompatible with server
2024-09-29 15:36:53.673 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 17.0 (Debian 17.0-1.pgdg120+1).
PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-09-29 15:37:54.093 UTC [1] FATAL:  database files are incompatible with server
2024-09-29 15:37:54.093 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 17.0 (Debian 17.0-1.pgdg120+1).
PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-09-29 15:38:54.480 UTC [1] FATAL:  database files are incompatible with server
2024-09-29 15:38:54.480 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 17.0 (Debian 17.0-1.pgdg120+1).
PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-09-29 15:39:54.935 UTC [1] FATAL:  database files are incompatible with server
2024-09-29 15:39:54.935 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 17.0 (Debian 17.0-1.pgdg120+1).
PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-09-29 15:40:55.324 UTC [1] FATAL:  database files are incompatible with server
2024-09-29 15:40:55.324 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 17.0 (Debian 17.0-1.pgdg120+1).
PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-09-29 15:41:55.719 UTC [1] FATAL:  database files are incompatible with server
2024-09-29 15:41:55.719 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 17.0 (Debian 17.0-1.pgdg120+1).
PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-09-29 15:42:56.127 UTC [1] FATAL:  database files are incompatible with server
2024-09-29 15:42:56.127 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 17.0 (Debian 17.0-1.pgdg120+1).
PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-09-29 15:43:56.576 UTC [1] FATAL:  database files are incompatible with server
2024-09-29 15:43:56.576 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 17.0 (Debian 17.0-1.pgdg120+1).
PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-09-29 15:44:56.977 UTC [1] FATAL:  database files are incompatible with server
2024-09-29 15:44:56.977 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 17.0 (Debian 17.0-1.pgdg120+1).
PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-09-29 15:45:57.374 UTC [1] FATAL:  database files are incompatible with server
2024-09-29 15:45:57.374 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 17.0 (Debian 17.0-1.pgdg120+1).
PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-09-29 15:46:57.771 UTC [1] FATAL:  database files are incompatible with server
2024-09-29 15:46:57.771 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 17.0 (Debian 17.0-1.pgdg120+1).
PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-09-29 15:47:58.250 UTC [1] FATAL:  database files are incompatible with server
2024-09-29 15:47:58.250 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 17.0 (Debian 17.0-1.pgdg120+1).
PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-09-29 15:48:58.665 UTC [1] FATAL:  database files are incompatible with server
2024-09-29 15:48:58.665 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 17.0 (Debian 17.0-1.pgdg120+1).
PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-09-29 15:49:59.075 UTC [1] FATAL:  database files are incompatible with server
2024-09-29 15:49:59.075 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 17.0 (Debian 17.0-1.pgdg120+1).
PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-09-29 15:50:59.471 UTC [1] FATAL:  database files are incompatible with server
2024-09-29 15:50:59.471 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 17.0 (Debian 17.0-1.pgdg120+1).
PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-09-29 15:51:59.859 UTC [1] FATAL:  database files are incompatible with server
2024-09-29 15:51:59.859 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 17.0 (Debian 17.0-1.pgdg120+1).
PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-09-29 15:53:00.239 UTC [1] FATAL:  database files are incompatible with server
2024-09-29 15:53:00.239 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 17.0 (Debian 17.0-1.pgdg120+1).
```

**Comment by uniquePWD** [comment]
Fixed: Locked the Postgres Database to version 16 and its all working again.
