### ISSUE TITLE
[BUG] nextcloud version-30.0.1

### ISSUE THREAD

**Issue by catmurdock** [linuxserver/docker-nextcloud#478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

after updating the latest image it failed to start.
I have done some basic troublshooting but it didnt work

### Expected Behavior

this happen after updating the latest docker image 

### Steps To Reproduce

I have redeploy the image, but still the same, downgrading is not supported 

### Environment

```markdown
- OS:Debian
- How docker service was installed: na
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "3"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - TZ=Europe/Amsterdam
      - MYSQL_DATABASE=nextcloud
      - MYSQL_HOST=192.168.2.xxx
      - MYSQL_PASSWORD=xxx
      - MYSQL_USER=xxx
    volumes:
      - /share/nextcloud_config:/config
      - /share/nextcloud_data:/data
    restart: unless-stopped
    
networks:
  Cloudflare_tunnel:
    external: true
```

### Container logs

```bash
Ugrading nextcloud from 30.0.0.14 ...
Setting permissions
An unhandled exception has been thrown:
Error: Failed opening required '/app/www/public/apps/files/composer/autoload.php' (include_path='/app/www/public/3rdparty/pear/archive_tar:/app/www/public/3rdparty/pear/console_getopt:/app/www/public/3rdparty/pear/pear-core-minimal/src:/app/www/public/3rdparty/pear/pear_exception:/app/www/public/apps') in /app/www/public/lib/private/legacy/OC_App.php:118
Stack trace:
#0 /app/www/public/lib/private/AppFramework/Bootstrap/Coordinator.php(76): OC_App::registerAutoloading()
#1 /app/www/public/lib/private/AppFramework/Bootstrap/Coordinator.php(48): OC\AppFramework\Bootstrap\Coordinator->registerApps()
#2 /app/www/public/lib/base.php(657): OC\AppFramework\Bootstrap\Coordinator->runInitialRegistration()
#3 /app/www/public/lib/base.php(1132): OC::init()
#4 /app/www/public/console.php(28): require_once('...')
#5 /app/www/public/occ(11): require_once('...')
#6 {main}Initializing finished
```

**Comment by j0nnymoe** [comment]
You've potentially got a broken third party app installed.
Also side note those ENV's for the sql details don't work in our container.

**Comment by catmurdock** [comment]
Maybe the theme is broken as wel

2024/10/18 22:14:48 [error] 438#438: *1 open() "/app/www/public/apps/theming/img/background/jenna-kim-the-globe.webp" failed (13: Permission denied), client: xx server: _, request: "GET /apps/theming/img/background/jenna-kim-the-globe.webp HTTP/1.1", host: "

**Comment by catmurdock** [comment]
#composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 1 install, 0 updates, 0 removals
  - Downloading bamarni/composer-bin-plugin (1.8.2)
  - Installing bamarni/composer-bin-plugin (1.8.2): Extracting archive
Generating optimized autoload files
Class FeedBackHandler located in ./core/ajax/update.php does not comply with psr-4 autoloading standard (rule: OC\Core\ => ./core). Skipping.
> [ $COMPOSER_DEV_MODE -eq 0 ] || composer bin all install
[bamarni-bin] Could not find any bin namespace.
> composer dump-autoload --no-dev
Generating optimized autoload files
Class FeedBackHandler located in ./core/ajax/update.php does not comply with psr-4 autoloading standard (rule: OC\Core\ => ./core). Skipping.
Generated optimized autoload files containing 2001 classes

:/app/www/public#occ
An unhandled exception has been thrown:
Error: Failed opening required '/app/www/public/apps/files/composer/autoload.php' (include_path='/app/www/public/3rdparty/pear/archive_tar:/app/www/public/3rdparty/pear/console_getopt:/app/www/public/3rdparty/pear/pear-core-minimal/src:/app/www/public/3rdparty/pear/pear_exception:/app/www/public/apps') in /app/www/public/lib/private/legacy/OC_App.php:118
Stack trace:
#0 /app/www/public/lib/private/AppFramework/Bootstrap/Coordinator.php(76): OC_App::registerAutoloading()
#1 /app/www/public/lib/private/AppFramework/Bootstrap/Coordinator.php(48): OC\AppFramework\Bootstrap\Coordinator->registerApps()
#2 /app/www/public/lib/base.php(657): OC\AppFramework\Bootstrap\Coordinator->runInitialRegistration()
#3 /app/www/public/lib/base.php(1132): OC::init()
#4 /app/www/public/console.php(28): require_once('...')
#5 /app/www/public/occ(11): require_once('...')

/app/www/public#composer update --no-scripts
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating optimized autoload files

**Comment by j0nnymoe** [comment]
You need to check nextcloud for any issues with the apps/themes you're using. This isn't a container issue.

**Comment by nurhalim88** [comment]
I had encounter same error, not able to downgrade with previous version. please help.. 😢
