### ISSUE TITLE
[BUG] Security Check Does Not Complete

### ISSUE THREAD

**Issue by Silun** [linuxserver/docker-nextcloud#483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The _Security & setup warnings_ self check under _administration settings_ -> _overview_ always throw this error:

**Error occurred while checking server setup.**

There are no related log entries about this, nextcloud.log only contains notices about 

```
[jsresourceloader] Error: Could not find resource files_pdfviewer/js/files_pdfviewer-main.js to load
	GET /settings/user
	from 111.222.333.13 by admin at Nov 22, 2024, 8:28:33 PM
```
as well as 2x from right after the installation, but never again:
```
[cron] Error: Not installed
	from ? by -- at Nov 22, 2024, 5:00:00 AM
```

### Expected Behavior

The check should complete.

### Steps To Reproduce

Start up the container, go through installation. After login, go to administration settings and be presented the error.

### Environment

```markdown
- OS: Ubuntu 24.04
- How docker service was installed: Via the script on https://get.docker.com
- I am not using a reverse proxy, I am just directly connecting to the container via port 4443 on the host.
- I tried with bind mounts and volumes but the issue remains.
```

### CPU architecture

x86-64

### Docker creation

```bash
---
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:previous
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - config:/config
      - data:/data
    ports:
      - 4443:443
    restart: unless-stopped


volumes:
  config:
  data:
```

### Container logs

```bash
# docker logs nextcloud
[migrations] started
[migrations] 01-nginx-site-confs-default: executing...
[migrations] 01-nginx-site-confs-default: succeeded
[migrations] 02-default-location: executing...
[migrations] 02-default-location: succeeded
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────
Linuxserver.io version: 29.0.9-ls21
Build-date: 2024-11-19T11:51:48+00:00
───────────────────────────────────────

Setting resolver to  127.0.0.11
Setting worker_processes to 2
generating self-signed keys in /config/keys, you can replace these with your own keys if required
##################################################################################################
Initializing nextcloud 29.0.9.2 (this can take a while) ...
Setting permissions
New nextcloud instance
Please run the web-based installer on first connect!
Initializing finished
After completing the web-based installer, restart the Nextcloud container to apply default memory caching and transactional file locking configurations.
Alternatively, you can apply your own configurations by editing /config/www/nextcloud/config/config.php following the documentation:
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/caching_configuration.html
https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/files_locking_transactional.html
[custom-init] No custom files found, skipping...
[ls.io-init] done.
Exception: Not installed in /app/www/public/lib/base.php:284
Stack trace:
#0 /app/www/public/lib/base.php(723): OC::checkInstalled()
#1 /app/www/public/lib/base.php(1189): OC::init()
#2 /app/www/public/cron.php(58): require_once('...')
#3 {main}
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────
Linuxserver.io version: 29.0.9-ls21
Build-date: 2024-11-19T11:51:48+00:00
───────────────────────────────────────

using keys found in /config/keys
System config value memcache.local set to string \OC\Memcache\APCu
System config value filelocking.enabled set to boolean true
System config value memcache.locking set to string \OC\Memcache\APCu
System config value upgrade.disable-web set to boolean true
[custom-init] No custom files found, skipping...
[ls.io-init] done.
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────
Linuxserver.io version: 29.0.9-ls21
Build-date: 2024-11-19T11:51:48+00:00
───────────────────────────────────────

using keys found in /config/keys
[custom-init] No custom files found, skipping...
[ls.io-init] done.
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────
Linuxserver.io version: 29.0.9-ls21
Build-date: 2024-11-19T11:51:48+00:00
───────────────────────────────────────

using keys found in /config/keys
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by j0nnymoe** [comment]
Happening during initial setup - needs to be tested internally.
https://canary.discord.com/channels/354974912613449730/1311096945913368616

**Comment by j0nnymoe** [comment]
Bug was happening on ubuntu 24.04 - potentially an issue with the distro/docker packages.

**Comment by Silun** [comment]
I should add that I **always** get a 504 gateway time-out error on this machine during installation. After refreshing the page, I am at the login page. Whenever I get the 504 error, the following is also true:

- Nextcloud does not ask me which apps to install, that part gets skipped over
- The first login attempt will fail, the second one will work
- I can see no entries in the log about this at all

And of course the error this issue is about occurs. I have tried to set timeouts to 3600 seconds prior to installation, via the config files in /config/, but to no avail. Nextcloud AIO works without a hitch on the same machine, so if the timeout interrupts the installation and it doesn't quite finish, then it would probably be something specific to LSIO's container - just an idea. I haven't seen this issue with other deployment methods so far.
